# This is only used for development purposes. You can not use Docker Compose on Heroku.
web:
  build: .
  volumes:
	- "./lib:/app/lib"
  ports:
    - "8080:8080"
  environment:
    PORT: 8080
    NODE_ENV: "development"
    LOG_LEVEL: "trace"
  command: "nodemon -L -x 'node' index.js | ./node_modules/.bin/bunyan -o short"
