# This compose configuration is used for development only
# Currently we deploy to Heroku, which uses the Procfile and environment configured in Heroku UI to set up the app environment
web:
    build: .
    volumes:
        - ./lib:/app/user/lib
        # Very useful to uncomment this to test obt integration
        # - ./../origami-build-tools:/app/user/node_modules/origami-build-tools
    working_dir: /app/user

    # The -L flag to nodemon allows it to see changes in mounted filesystems
    command: "nodemon -L -x 'node' index.js | ./node_modules/.bin/bunyan -o short"
    ports:
        - "8080:8080"
    environment:
        PORT: 8080
        NODE_ENV: "development"
        LOG_LEVEL: "trace"
