# This is only used for development purposes. You can not use Docker Compose on Heroku.
web:
  build: .
  container_name: origami-buildservice-dev
  volumes:
    - "./lib:/app/lib"
    - "./deprecated:/app/deprecated"
  ports:
    - "8080:8080"
  environment:
    PORT: 8080
    NODE_ENV: "development"
    LOG_LEVEL: "trace"
  command: "nodemon --legacy-watch index.js | ./node_modules/.bin/bunyan -o short"
