name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.4
      with:
        node-version: 12.x
    - run: npm install -g "npm@^7"
    - run: npm ci
    - run: make verify
    - run: make test-unit-coverage
      env:
        GITHUB_TOKEN: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
    - run: make test-integration
      env:
        GITHUB_TOKEN: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
    - run: make test-old
      env:
        GITHUB_TOKEN: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
