name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - run: git config --global url."https://${{ secrets.ORIGAMI_GITHUB_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
    - uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x
    - run: npm install -g "npm@^7"
    - run: npm ci
    - run: make verify
    - run: make test-unit-coverage
      env:
        ORIGAMI_GITHUB_TOKEN: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
    - run: make test-integration
      env:
        ORIGAMI_GITHUB_TOKEN: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
